# Use a imagem base com o servidor web (exemplo usando o Apache)
FROM httpd:latest

# Copie seus arquivos do projeto para o diretório do servidor web no contêiner
COPY ./tcc.txt /usr/local/apache2/htdocs/
